# Generated by Django 5.0.8 on 2024-08-09 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicSearch",
            "0002_city_dayweek_speciality_state_neighborhood_address_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="addresses",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="addresses",
                to="medicSearch.address",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="specialties",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="specialties",
                to="medicSearch.speciality",
            ),
        ),
    ]
