# Generated by Django 5.0.8 on 2024-08-09 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicSearch",
            "0003_profile_addresses_profile_favorites_profile_image_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="addresses",
            field=models.ManyToManyField(
                blank=True, related_name="addresses", to="medicSearch.address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="specialties",
            field=models.ManyToManyField(
                blank=True, related_name="specialties", to="medicSearch.speciality"
            ),
        ),
    ]
